---
title: "SQL connection template"
author: Data
editor: visual
---

```{r setup, include=FALSE}
library(DBI) # 
library(RMariaDB) # Dont have to neccessarily  
library(dplyr)
```

```{r connection-parameters}
# Parameters
user <- 'ursula.podosenin92' # Username
password <- 'ursula.podosenin92' # Password
database <- 'ursula.podosenin92' 
host <- 'cunydata607sql.mysql.database.azure.com' # address of the server
port <- 3306
```

```{r connection}
# Connect to the database
connection <- DBI::dbConnect(drv = MariaDB(), 
                             dbname = database,
                             host = host, 
                             port = port, 
                             user = user, 
                             password = password)
```

```{r fetch}
# Fetch results
tbl(connection, "Persons") %>% # name of table goes in the quotation
  collect() -> data
```

```{r disconnect}
# Disconnect from the database
DBI::dbDisconnect(connection)
```

```{r preview}
# Preview you shouldn't have to connect again
data
```

## 
